.pragma library

var strings = {
    "en-us": {
        bucket_main: "Main",
        bucket_used: "Used",
        bucket_practice: "In practice",
        bucket_unused: "Unused",
        principal: "MAIN",
        roulette_format: "ROULETTE",
        spin_roulette: "SPIN ROULETTE",
        roulette_spinning: "SPINNING…",

        roulette_maker_short: "MAKER",
        roulette_maker: "ROULETTE MAKER",
        roulette_numbers: "Choose the exact number of numbered slots.",
        roulette_weight_hint: "Use - and + on each hero to assign exact slots. Probability updates automatically.",
        roulette_slots: "slots",
        roulette_roles: "Allowed roles",
        roulette_select_all: "SELECT ALL",
        roulette_clear: "CLEAR",
        roulette_search: "Search heroes",
        roulette_selected: "heroes selected",
        roulette_build: "BUILD ROULETTE",
        roulette_pick_heroes: "Choose at least one hero.",
        roulette_ready_help: "Adjust the roulette and build it before spinning.",
        roulette_built: "Roulette ready.",
        roulette_winner: "Winner",
        roulette_custom_title: "CUSTOM HERO ROULETTE",
        roulette_spin_hint: "SPIN",
        roulette_rule_note: "Every spin is independent. The previous winner may win again; the slots define the probability.",
        roulette_entries: "NUMBERED SLOTS",
        roulette_not_built: "Build the roulette to see its numbered slots.",
        profile_connection: "PROFILE CONNECTION",
        manual: "MANUAL",
        synced: "SYNCED WITH OVERFAST",
        hybrid: "HYBRID",
        battletag: "BattleTag (Player#1234)",
        synchronize: "SYNC NOW",
        lock: "LOCK",
        unlock: "UNLOCK",
        manual_help: "Works locally without BattleTag or API.",
        synced_help: "OverFast updates every hero classification.",
        hybrid_help: "OverFast updates unlocked heroes; manual changes stay locked.",
        sync_need_profile: "Select or create a profile first.",
        sync_need_battletag: "Enter a BattleTag before syncing.",
        sync_searching: "Searching and synchronizing with OverFast…",
        sync_loaded: "Profile synchronized.",
        sync_failed: "Synchronization failed",
        sync_helper_warning: "Local sync helper is unavailable; manual mode still works.",
        sync_save_failed: "Could not save sync settings",
        heroes_updated: "heroes updated",
        classification_note: "Main ≥30 h · Used ≥5 h · Practice >0 h · Unused 0 h",
        relevant_use_note: "Relevant use threshold: 5 hours",
        linked_profile: "BattleTag linked to the current profile.",
        link_profile: "LINK TO CURRENT PROFILE",
        player: "Player",
        roulette: "ROULETTE", statistics: "STATISTICS", player_search: "PLAYER SEARCH",
        search_hint: "BattleTag or player name", search: "SEARCH", load_direct: "LOAD ID",
        search_results: "SEARCH RESULTS", no_results: "No players found.", select_player: "Select a player to view statistics.",
        profile_private: "This career profile is private or has no visible statistics.",
        overview: "OVERVIEW", heroes: "HERO USAGE", roles: "ROLES", career: "CAREER", api: "OVERFAST API",
        all_modes: "All modes", quickplay: "Quick Play", competitive: "Competitive",
        all_platforms: "All platforms", pc: "PC", console: "Console", refresh: "REFRESH",
        time_played: "Time played", games: "Games", wins: "Wins", losses: "Losses", winrate: "Win rate", kda: "KDA",
        eliminations: "Eliminations", assists: "Assists", deaths: "Deaths", damage: "Damage", healing: "Healing",
        usage: "Usage", last_updated: "Last updated", endorsement: "Endorsement", rank: "Competitive ranks",
        no_stats: "No visible statistics for these filters.", no_comp: "No competitive rank is visible.",
        career_mode_note: "Career details require a game mode. Choose a hero or all heroes.",
        hero: "Hero", all_heroes: "All heroes", load_career: "LOAD CAREER DETAILS",
        endpoint: "Endpoint", run_endpoint: "RUN ENDPOINT", response_preview: "RESPONSE PREVIEW",
        response_truncated: "The preview was shortened to keep the interface responsive.",
        searching: "Searching OverFast…", loading: "Loading player data…", loaded: "Player data loaded.",
        request_failed: "OverFast request failed", invalid_id: "Enter a BattleTag or player ID.",
        api_note: "Player data comes from OverFast API and Blizzard public career profiles. Private profiles cannot be read.",
        category: "Category", value: "Value", public_profile: "Public profile", private_profile: "Private profile",
        direct_help: "Use # or - in the BattleTag. Example: Player#1234 or Player-1234.",
        top_hero: "Most played hero", total_usage: "Share of total visible playtime", season: "Season",
        player_id: "Player ID", title: "Title", open_queue: "Open Queue", tank: "Tank", support: "Support"
    },
    "es-mx": {
        bucket_main: "Main",
        bucket_used: "Usado",
        bucket_practice: "En práctica",
        bucket_unused: "No usado",
        principal: "PRINCIPAL",
        roulette_format: "RULETA",
        spin_roulette: "GIRAR RULETA",
        roulette_spinning: "GIRANDO…",

        roulette_maker_short: "MAKER",
        roulette_maker: "CREADOR DE RULETA",
        roulette_numbers: "Elige la cantidad exacta de casillas numeradas.",
        roulette_weight_hint: "Usa - y + en cada héroe para darle casillas exactas. El porcentaje se calcula solo.",
        roulette_slots: "casillas",
        roulette_roles: "Roles permitidos",
        roulette_select_all: "SELECCIONAR TODOS",
        roulette_clear: "LIMPIAR",
        roulette_search: "Buscar héroes",
        roulette_selected: "héroes seleccionados",
        roulette_build: "CREAR RULETA",
        roulette_pick_heroes: "Elige al menos un héroe.",
        roulette_ready_help: "Configura la ruleta y créala antes de girar.",
        roulette_built: "Ruleta lista.",
        roulette_winner: "Ganador",
        roulette_custom_title: "RULETA PERSONALIZADA DE HÉROES",
        roulette_spin_hint: "GIRAR",
        roulette_rule_note: "Cada giro es independiente. El ganador anterior puede repetirse; las casillas definen la probabilidad.",
        roulette_entries: "CASILLAS NUMERADAS",
        roulette_not_built: "Crea la ruleta para ver sus casillas numeradas.",
        profile_connection: "CONEXIÓN DEL PERFIL",
        manual: "MANUAL",
        synced: "SINCRONIZADO CON OVERFAST",
        hybrid: "HÍBRIDO",
        battletag: "BattleTag (Jugador#1234)",
        synchronize: "SINCRONIZAR AHORA",
        lock: "FIJAR",
        unlock: "LIBERAR",
        manual_help: "Funciona localmente sin BattleTag ni API.",
        synced_help: "OverFast actualiza toda la clasificación de héroes.",
        hybrid_help: "OverFast actualiza héroes libres; los cambios manuales quedan fijados.",
        sync_need_profile: "Primero selecciona o crea un perfil.",
        sync_need_battletag: "Escribe un BattleTag antes de sincronizar.",
        sync_searching: "Buscando y sincronizando con OverFast…",
        sync_loaded: "Perfil sincronizado.",
        sync_failed: "Falló la sincronización",
        sync_helper_warning: "El auxiliar local no está disponible; el modo Manual sigue funcionando.",
        sync_save_failed: "No se pudo guardar la sincronización",
        heroes_updated: "héroes actualizados",
        classification_note: "Main ≥30 h · Usado ≥5 h · En práctica >0 h · No usado 0 h",
        relevant_use_note: "Uso relevante: 5 horas",
        linked_profile: "BattleTag vinculado al perfil actual.",
        link_profile: "VINCULAR AL PERFIL ACTUAL",
        player: "Jugador",
        roulette: "RULETA", statistics: "ESTADÍSTICAS", player_search: "BUSCAR JUGADOR",
        search_hint: "BattleTag o nombre del jugador", search: "BUSCAR", load_direct: "CARGAR ID",
        search_results: "RESULTADOS DE BÚSQUEDA", no_results: "No se encontraron jugadores.", select_player: "Selecciona un jugador para ver sus estadísticas.",
        profile_private: "El perfil de carrera es privado o no tiene estadísticas visibles.",
        overview: "RESUMEN", heroes: "USO DE HÉROES", roles: "ROLES", career: "CARRERA", api: "API OVERFAST",
        all_modes: "Todos los modos", quickplay: "Partida rápida", competitive: "Competitivo",
        all_platforms: "Todas las plataformas", pc: "PC", console: "Consola", refresh: "ACTUALIZAR",
        time_played: "Tiempo jugado", games: "Partidas", wins: "Victorias", losses: "Derrotas", winrate: "Porcentaje de victoria", kda: "KDA",
        eliminations: "Eliminaciones", assists: "Asistencias", deaths: "Muertes", damage: "Daño", healing: "Sanación",
        usage: "Uso", last_updated: "Última actualización", endorsement: "Nivel de recomendación", rank: "Rangos competitivos",
        no_stats: "No hay estadísticas visibles con estos filtros.", no_comp: "No hay un rango competitivo visible.",
        career_mode_note: "Los detalles de carrera requieren un modo. Elige un héroe o todos los héroes.",
        hero: "Héroe", all_heroes: "Todos los héroes", load_career: "CARGAR DETALLES DE CARRERA",
        endpoint: "Endpoint", run_endpoint: "EJECUTAR ENDPOINT", response_preview: "VISTA PREVIA DE RESPUESTA",
        response_truncated: "La vista previa se recortó para mantener fluida la interfaz.",
        searching: "Buscando en OverFast…", loading: "Cargando datos del jugador…", loaded: "Datos del jugador cargados.",
        request_failed: "Falló la solicitud a OverFast", invalid_id: "Escribe un BattleTag o ID de jugador.",
        api_note: "Los datos provienen de OverFast API y de los perfiles públicos de carrera de Blizzard. Los perfiles privados no pueden leerse.",
        category: "Categoría", value: "Valor", public_profile: "Perfil público", private_profile: "Perfil privado",
        direct_help: "Puedes usar # o - en el BattleTag. Ejemplo: Jugador#1234 o Jugador-1234.",
        top_hero: "Héroe más usado", total_usage: "Parte del tiempo total visible", season: "Temporada",
        player_id: "ID del jugador", title: "Título", open_queue: "Cola abierta", tank: "Tanque", support: "Apoyo"
    },
    "es-es": {
        bucket_main: "Main",
        bucket_used: "Usado",
        bucket_practice: "En práctica",
        bucket_unused: "No usado",
        principal: "PRINCIPAL",
        roulette_format: "RULETA",
        spin_roulette: "GIRAR RULETA",
        roulette_spinning: "GIRANDO…",

        roulette_maker_short: "MAKER",
        roulette_maker: "CREADOR DE RULETA",
        roulette_numbers: "Elige el número exacto de casillas numeradas.",
        roulette_weight_hint: "Usa - y + en cada héroe para asignarle casillas exactas. El porcentaje se calcula solo.",
        roulette_slots: "casillas",
        roulette_roles: "Roles permitidos",
        roulette_select_all: "SELECCIONAR TODOS",
        roulette_clear: "LIMPIAR",
        roulette_search: "Buscar héroes",
        roulette_selected: "héroes seleccionados",
        roulette_build: "CREAR RULETA",
        roulette_pick_heroes: "Elige al menos un héroe.",
        roulette_ready_help: "Configura la ruleta y créala antes de girar.",
        roulette_built: "Ruleta preparada.",
        roulette_winner: "Ganador",
        roulette_custom_title: "RULETA PERSONALIZADA DE HÉROES",
        roulette_spin_hint: "GIRAR",
        roulette_rule_note: "Cada giro es independiente. El ganador anterior puede repetirse; las casillas definen la probabilidad.",
        roulette_entries: "CASILLAS NUMERADAS",
        roulette_not_built: "Crea la ruleta para ver sus casillas numeradas.",
        profile_connection: "CONEXIÓN DEL PERFIL",
        manual: "MANUAL",
        synced: "SINCRONIZADO CON OVERFAST",
        hybrid: "HÍBRIDO",
        battletag: "BattleTag (Jugador#1234)",
        synchronize: "SINCRONIZAR AHORA",
        lock: "FIJAR",
        unlock: "LIBERAR",
        manual_help: "Funciona localmente sin BattleTag ni API.",
        synced_help: "OverFast actualiza toda la clasificación de héroes.",
        hybrid_help: "OverFast actualiza los héroes libres; los cambios manuales quedan fijados.",
        sync_need_profile: "Primero selecciona o crea un perfil.",
        sync_need_battletag: "Introduce un BattleTag antes de sincronizar.",
        sync_searching: "Buscando y sincronizando con OverFast…",
        sync_loaded: "Perfil sincronizado.",
        sync_failed: "Ha fallado la sincronización",
        sync_helper_warning: "El asistente local no está disponible; el modo Manual sigue funcionando.",
        sync_save_failed: "No se ha podido guardar la sincronización",
        heroes_updated: "héroes actualizados",
        classification_note: "Main ≥30 h · Usado ≥5 h · En práctica >0 h · No usado 0 h",
        relevant_use_note: "Uso relevante: 5 horas",
        linked_profile: "BattleTag vinculado al perfil actual.",
        link_profile: "VINCULAR AL PERFIL ACTUAL",
        player: "Jugador",
        roulette: "RULETA", statistics: "ESTADÍSTICAS", player_search: "BUSCAR JUGADOR",
        search_hint: "BattleTag o nombre del jugador", search: "BUSCAR", load_direct: "CARGAR ID",
        search_results: "RESULTADOS DE BÚSQUEDA", no_results: "No se han encontrado jugadores.", select_player: "Selecciona un jugador para ver sus estadísticas.",
        profile_private: "El perfil de carrera es privado o no tiene estadísticas visibles.",
        overview: "RESUMEN", heroes: "USO DE HÉROES", roles: "ROLES", career: "CARRERA", api: "API OVERFAST",
        all_modes: "Todos los modos", quickplay: "Partida rápida", competitive: "Competitivo",
        all_platforms: "Todas las plataformas", pc: "PC", console: "Consola", refresh: "ACTUALIZAR",
        time_played: "Tiempo jugado", games: "Partidas", wins: "Victorias", losses: "Derrotas", winrate: "Porcentaje de victorias", kda: "KDA",
        eliminations: "Eliminaciones", assists: "Asistencias", deaths: "Muertes", damage: "Daño", healing: "Sanación",
        usage: "Uso", last_updated: "Última actualización", endorsement: "Nivel de recomendación", rank: "Rangos competitivos",
        no_stats: "No hay estadísticas visibles con estos filtros.", no_comp: "No hay ningún rango competitivo visible.",
        career_mode_note: "Los detalles de carrera requieren un modo. Elige un héroe o todos los héroes.",
        hero: "Héroe", all_heroes: "Todos los héroes", load_career: "CARGAR DETALLES DE CARRERA",
        endpoint: "Endpoint", run_endpoint: "EJECUTAR ENDPOINT", response_preview: "VISTA PREVIA DE LA RESPUESTA",
        response_truncated: "La vista previa se ha recortado para mantener fluida la interfaz.",
        searching: "Buscando en OverFast…", loading: "Cargando los datos del jugador…", loaded: "Datos del jugador cargados.",
        request_failed: "Ha fallado la solicitud a OverFast", invalid_id: "Introduce un BattleTag o ID de jugador.",
        api_note: "Los datos proceden de OverFast API y de los perfiles públicos de carrera de Blizzard. Los perfiles privados no se pueden leer.",
        category: "Categoría", value: "Valor", public_profile: "Perfil público", private_profile: "Perfil privado",
        direct_help: "Puedes usar # o - en el BattleTag. Ejemplo: Jugador#1234 o Jugador-1234.",
        top_hero: "Héroe más usado", total_usage: "Parte del tiempo total visible", season: "Temporada",
        player_id: "ID del jugador", title: "Título", open_queue: "Cola abierta", tank: "Tanque", support: "Apoyo"
    },
    "ja-jp": {
        bucket_main: "メイン",
        bucket_used: "使用済み",
        bucket_practice: "練習中",
        bucket_unused: "未使用",
        principal: "メイン",
        roulette_format: "ルーレット",
        spin_roulette: "ルーレットを回す",
        roulette_spinning: "回転中…",

        roulette_maker_short: "作成",
        roulette_maker: "ルーレット作成",
        roulette_numbers: "番号付きスロット数を指定します。",
        roulette_weight_hint: "各ヒーローの - と + で枠数を指定します。確率は自動で計算されます。",
        roulette_slots: "スロット",
        roulette_roles: "対象ロール",
        roulette_select_all: "すべて選択",
        roulette_clear: "クリア",
        roulette_search: "ヒーロー検索",
        roulette_selected: "人のヒーローを選択",
        roulette_build: "ルーレットを作成",
        roulette_pick_heroes: "ヒーローを1人以上選択してください。",
        roulette_ready_help: "設定後にルーレットを作成してから回してください。",
        roulette_built: "ルーレットを作成しました。",
        roulette_winner: "当選",
        roulette_custom_title: "カスタムヒーロールーレット",
        roulette_spin_hint: "回す",
        roulette_rule_note: "選択した各ヒーローは最低1回登場し、余分なスロットは選択プールから重複します。",
        roulette_entries: "番号付きスロット",
        roulette_not_built: "ルーレットを作成すると番号付きスロットが表示されます。",
        profile_connection: "プロフィール連携",
        manual: "手動",
        synced: "OVERFAST同期",
        hybrid: "ハイブリッド",
        battletag: "BattleTag（Player#1234）",
        synchronize: "今すぐ同期",
        lock: "固定",
        unlock: "解除",
        manual_help: "BattleTagやAPIなしでローカル動作します。",
        synced_help: "OverFastが全ヒーローの分類を更新します。",
        hybrid_help: "固定していないヒーローのみ同期し、手動変更を保持します。",
        sync_need_profile: "先にプロフィールを選択または作成してください。",
        sync_need_battletag: "同期前にBattleTagを入力してください。",
        sync_searching: "OverFastで検索・同期中…",
        sync_loaded: "プロフィールを同期しました。",
        sync_failed: "同期に失敗しました",
        sync_helper_warning: "ローカル同期機能を利用できません。手動モードは使用できます。",
        sync_save_failed: "同期設定を保存できませんでした",
        heroes_updated: "人のヒーローを更新",
        classification_note: "メイン30時間以上・使用済み5時間以上・練習中0時間超・未使用0時間",
        relevant_use_note: "使用済みの基準：5時間",
        linked_profile: "BattleTagを現在のプロフィールに連携しました。",
        link_profile: "現在のプロフィールに連携",
        player: "プレイヤー",
        roulette: "ルーレット", statistics: "統計", player_search: "プレイヤー検索",
        search_hint: "BattleTag またはプレイヤー名", search: "検索", load_direct: "IDを読み込む",
        search_results: "検索結果", no_results: "プレイヤーが見つかりませんでした。", select_player: "統計を表示するプレイヤーを選択してください。",
        profile_private: "キャリアプロフィールが非公開、または表示できる統計がありません。",
        overview: "概要", heroes: "ヒーロー使用率", roles: "ロール", career: "キャリア", api: "OVERFAST API",
        all_modes: "すべてのモード", quickplay: "クイック・プレイ", competitive: "ライバル・プレイ",
        all_platforms: "すべてのプラットフォーム", pc: "PC", console: "コンソール", refresh: "更新",
        time_played: "プレイ時間", games: "試合", wins: "勝利", losses: "敗北", winrate: "勝率", kda: "KDA",
        eliminations: "キル", assists: "アシスト", deaths: "デス", damage: "ダメージ", healing: "回復",
        usage: "使用率", last_updated: "最終更新", endorsement: "推薦レベル", rank: "ライバル・プレイのランク",
        no_stats: "この条件で表示できる統計はありません。", no_comp: "表示できるランクがありません。",
        career_mode_note: "キャリア詳細にはゲームモードが必要です。ヒーローまたは全ヒーローを選択してください。",
        hero: "ヒーロー", all_heroes: "全ヒーロー", load_career: "キャリア詳細を読み込む",
        endpoint: "エンドポイント", run_endpoint: "実行", response_preview: "レスポンスプレビュー",
        response_truncated: "動作を軽くするため、プレビューを短縮しました。",
        searching: "OverFastで検索中…", loading: "プレイヤーデータを読み込み中…", loaded: "プレイヤーデータを読み込みました。",
        request_failed: "OverFastへのリクエストに失敗しました", invalid_id: "BattleTagまたはプレイヤーIDを入力してください。",
        api_note: "データはOverFast APIとBlizzardの公開キャリアプロフィールから取得します。非公開プロフィールは読み取れません。",
        category: "カテゴリー", value: "値", public_profile: "公開プロフィール", private_profile: "非公開プロフィール",
        direct_help: "BattleTagには # または - を使用できます。例: Player#1234 / Player-1234",
        top_hero: "最も使用したヒーロー", total_usage: "表示可能な総プレイ時間に占める割合", season: "シーズン",
        player_id: "プレイヤーID", title: "称号", open_queue: "オープンキュー", tank: "タンク", support: "サポート"
    },
    "pt-br": {
        bucket_main: "Main",
        bucket_used: "Usado",
        bucket_practice: "Em prática",
        bucket_unused: "Sem uso",
        principal: "PRINCIPAL",
        roulette_format: "ROLETA",
        spin_roulette: "GIRAR ROLETA",
        roulette_spinning: "GIRANDO…",

        roulette_maker_short: "CRIADOR",
        roulette_maker: "CRIADOR DE ROLETA",
        roulette_numbers: "Escolha a quantidade exata de casas numeradas.",
        roulette_weight_hint: "Use - e + em cada herói para definir casas exatas. A probabilidade é calculada automaticamente.",
        roulette_slots: "casas",
        roulette_roles: "Funções permitidas",
        roulette_select_all: "SELECIONAR TODOS",
        roulette_clear: "LIMPAR",
        roulette_search: "Buscar heróis",
        roulette_selected: "heróis selecionados",
        roulette_build: "CRIAR ROLETA",
        roulette_pick_heroes: "Escolha pelo menos um herói.",
        roulette_ready_help: "Configure e crie a roleta antes de girar.",
        roulette_built: "Roleta pronta.",
        roulette_winner: "Vencedor",
        roulette_custom_title: "ROLETA PERSONALIZADA DE HERÓIS",
        roulette_spin_hint: "GIRAR",
        roulette_rule_note: "Cada herói escolhido aparece ao menos uma vez; casas extras repetem heróis do grupo selecionado.",
        roulette_entries: "CASAS NUMERADAS",
        roulette_not_built: "Crie a roleta para ver as casas numeradas.",
        profile_connection: "CONEXÃO DO PERFIL",
        manual: "MANUAL",
        synced: "SINCRONIZADO COM OVERFAST",
        hybrid: "HÍBRIDO",
        battletag: "BattleTag (Jogador#1234)",
        synchronize: "SINCRONIZAR AGORA",
        lock: "BLOQUEAR",
        unlock: "DESBLOQUEAR",
        manual_help: "Funciona localmente sem BattleTag nem API.",
        synced_help: "O OverFast atualiza toda a classificação de heróis.",
        hybrid_help: "O OverFast atualiza heróis livres; alterações manuais ficam bloqueadas.",
        sync_need_profile: "Selecione ou crie um perfil primeiro.",
        sync_need_battletag: "Digite um BattleTag antes de sincronizar.",
        sync_searching: "Buscando e sincronizando com o OverFast…",
        sync_loaded: "Perfil sincronizado.",
        sync_failed: "Falha na sincronização",
        sync_helper_warning: "O auxiliar local não está disponível; o modo Manual continua funcionando.",
        sync_save_failed: "Não foi possível salvar a sincronização",
        heroes_updated: "heróis atualizados",
        classification_note: "Main ≥30 h · Usado ≥5 h · Em prática >0 h · Sem uso 0 h",
        relevant_use_note: "Uso relevante: 5 horas",
        linked_profile: "BattleTag vinculado ao perfil atual.",
        link_profile: "VINCULAR AO PERFIL ATUAL",
        player: "Jogador",
        roulette: "ROLETA", statistics: "ESTATÍSTICAS", player_search: "BUSCAR JOGADOR",
        search_hint: "BattleTag ou nome do jogador", search: "BUSCAR", load_direct: "CARREGAR ID",
        search_results: "RESULTADOS", no_results: "Nenhum jogador encontrado.", select_player: "Selecione um jogador para ver as estatísticas.",
        profile_private: "O perfil de carreira é privado ou não possui estatísticas visíveis.",
        overview: "RESUMO", heroes: "USO DE HERÓIS", roles: "FUNÇÕES", career: "CARREIRA", api: "API OVERFAST",
        all_modes: "Todos os modos", quickplay: "Jogo Rápido", competitive: "Competitivo",
        all_platforms: "Todas as plataformas", pc: "PC", console: "Console", refresh: "ATUALIZAR",
        time_played: "Tempo jogado", games: "Partidas", wins: "Vitórias", losses: "Derrotas", winrate: "Taxa de vitória", kda: "KDA",
        eliminations: "Eliminações", assists: "Assistências", deaths: "Mortes", damage: "Dano", healing: "Cura",
        usage: "Uso", last_updated: "Última atualização", endorsement: "Endosso", rank: "Ranks competitivos",
        no_stats: "Não há estatísticas visíveis com estes filtros.", no_comp: "Não há rank competitivo visível.",
        career_mode_note: "Os detalhes da carreira exigem um modo. Escolha um herói ou todos.",
        hero: "Herói", all_heroes: "Todos os heróis", load_career: "CARREGAR DETALHES DA CARREIRA",
        endpoint: "Endpoint", run_endpoint: "EXECUTAR ENDPOINT", response_preview: "PRÉVIA DA RESPOSTA",
        response_truncated: "A prévia foi reduzida para manter a interface responsiva.",
        searching: "Buscando no OverFast…", loading: "Carregando dados do jogador…", loaded: "Dados do jogador carregados.",
        request_failed: "Falha na solicitação ao OverFast", invalid_id: "Digite um BattleTag ou ID de jogador.",
        api_note: "Os dados vêm da OverFast API e dos perfis públicos de carreira da Blizzard. Perfis privados não podem ser lidos.",
        category: "Categoria", value: "Valor", public_profile: "Perfil público", private_profile: "Perfil privado",
        direct_help: "Use # ou - no BattleTag. Exemplo: Jogador#1234 ou Jogador-1234.",
        top_hero: "Herói mais jogado", total_usage: "Parcela do tempo total visível", season: "Temporada",
        player_id: "ID do jogador", title: "Título", open_queue: "Fila aberta", tank: "Tanque", support: "Suporte"
    },
    "fr-fr": {
        bucket_main: "Main",
        bucket_used: "Utilisé",
        bucket_practice: "En pratique",
        bucket_unused: "Non utilisé",
        principal: "PRINCIPAL",
        roulette_format: "ROULETTE",
        spin_roulette: "LANCER LA ROULETTE",
        roulette_spinning: "TIRAGE…",

        roulette_maker_short: "CRÉATEUR",
        roulette_maker: "CRÉATEUR DE ROULETTE",
        roulette_numbers: "Choisissez le nombre exact de cases numérotées.",
        roulette_weight_hint: "Utilisez - et + sur chaque héros pour attribuer ses cases. La probabilité est calculée automatiquement.",
        roulette_slots: "cases",
        roulette_roles: "Rôles autorisés",
        roulette_select_all: "TOUT SÉLECTIONNER",
        roulette_clear: "EFFACER",
        roulette_search: "Rechercher des héros",
        roulette_selected: "héros sélectionnés",
        roulette_build: "CRÉER LA ROULETTE",
        roulette_pick_heroes: "Choisissez au moins un héros.",
        roulette_ready_help: "Configurez puis créez la roulette avant de la lancer.",
        roulette_built: "Roulette prête.",
        roulette_winner: "Gagnant",
        roulette_custom_title: "ROULETTE DE HÉROS PERSONNALISÉE",
        roulette_spin_hint: "LANCER",
        roulette_rule_note: "Chaque héros choisi apparaît au moins une fois ; les cases supplémentaires répètent les héros du groupe sélectionné.",
        roulette_entries: "CASES NUMÉROTÉES",
        roulette_not_built: "Créez la roulette pour afficher ses cases numérotées.",
        profile_connection: "CONNEXION DU PROFIL",
        manual: "MANUEL",
        synced: "SYNCHRONISÉ AVEC OVERFAST",
        hybrid: "HYBRIDE",
        battletag: "BattleTag (Joueur#1234)",
        synchronize: "SYNCHRONISER",
        lock: "VERROU",
        unlock: "DÉVERROU",
        manual_help: "Fonctionne localement sans BattleTag ni API.",
        synced_help: "OverFast met à jour tous les classements de héros.",
        hybrid_help: "OverFast met à jour les héros libres et conserve les changements verrouillés.",
        sync_need_profile: "Sélectionnez ou créez d’abord un profil.",
        sync_need_battletag: "Saisissez un BattleTag avant la synchronisation.",
        sync_searching: "Recherche et synchronisation OverFast…",
        sync_loaded: "Profil synchronisé.",
        sync_failed: "Échec de la synchronisation",
        sync_helper_warning: "Le service local est indisponible ; le mode Manuel fonctionne toujours.",
        sync_save_failed: "Impossible d’enregistrer la synchronisation",
        heroes_updated: "héros mis à jour",
        classification_note: "Main ≥30 h · Utilisé ≥5 h · En pratique >0 h · Non utilisé 0 h",
        relevant_use_note: "Utilisation pertinente : 5 heures",
        linked_profile: "BattleTag associé au profil actuel.",
        link_profile: "ASSOCIER AU PROFIL ACTUEL",
        player: "Joueur",
        roulette: "ROULETTE", statistics: "STATISTIQUES", player_search: "RECHERCHER UN JOUEUR",
        search_hint: "BattleTag ou nom du joueur", search: "RECHERCHER", load_direct: "CHARGER L’ID",
        search_results: "RÉSULTATS", no_results: "Aucun joueur trouvé.", select_player: "Sélectionnez un joueur pour afficher ses statistiques.",
        profile_private: "Le profil de carrière est privé ou ne contient aucune statistique visible.",
        overview: "RÉSUMÉ", heroes: "UTILISATION DES HÉROS", roles: "RÔLES", career: "CARRIÈRE", api: "API OVERFAST",
        all_modes: "Tous les modes", quickplay: "Partie rapide", competitive: "Compétitif",
        all_platforms: "Toutes les plateformes", pc: "PC", console: "Console", refresh: "ACTUALISER",
        time_played: "Temps de jeu", games: "Parties", wins: "Victoires", losses: "Défaites", winrate: "Taux de victoire", kda: "KDA",
        eliminations: "Éliminations", assists: "Assistances", deaths: "Morts", damage: "Dégâts", healing: "Soins",
        usage: "Utilisation", last_updated: "Dernière mise à jour", endorsement: "Recommandation", rank: "Rangs compétitifs",
        no_stats: "Aucune statistique visible avec ces filtres.", no_comp: "Aucun rang compétitif visible.",
        career_mode_note: "Les détails de carrière nécessitent un mode. Choisissez un héros ou tous les héros.",
        hero: "Héros", all_heroes: "Tous les héros", load_career: "CHARGER LES DÉTAILS",
        endpoint: "Endpoint", run_endpoint: "EXÉCUTER", response_preview: "APERÇU DE LA RÉPONSE",
        response_truncated: "L’aperçu a été raccourci pour préserver la fluidité de l’interface.",
        searching: "Recherche dans OverFast…", loading: "Chargement des données du joueur…", loaded: "Données du joueur chargées.",
        request_failed: "Échec de la requête OverFast", invalid_id: "Saisissez un BattleTag ou un identifiant de joueur.",
        api_note: "Les données proviennent d’OverFast API et des profils de carrière publics de Blizzard. Les profils privés ne peuvent pas être lus.",
        category: "Catégorie", value: "Valeur", public_profile: "Profil public", private_profile: "Profil privé",
        direct_help: "Utilisez # ou - dans le BattleTag. Exemple : Joueur#1234 ou Joueur-1234.",
        top_hero: "Héros le plus joué", total_usage: "Part du temps de jeu visible", season: "Saison",
        player_id: "ID du joueur", title: "Titre", open_queue: "File libre", tank: "Tank", support: "Soutien"
    },
    "de-de": {
        bucket_main: "Main",
        bucket_used: "Verwendet",
        bucket_practice: "In Übung",
        bucket_unused: "Unbenutzt",
        principal: "START",
        roulette_format: "ROULETTE",
        spin_roulette: "ROULETTE DREHEN",
        roulette_spinning: "DREHT…",

        roulette_maker_short: "EDITOR",
        roulette_maker: "ROULETTEN-EDITOR",
        roulette_numbers: "Wähle die genaue Anzahl nummerierter Felder.",
        roulette_weight_hint: "Lege mit - und + für jeden Helden die Felder fest. Die Wahrscheinlichkeit wird automatisch berechnet.",
        roulette_slots: "Felder",
        roulette_roles: "Erlaubte Rollen",
        roulette_select_all: "ALLE AUSWÄHLEN",
        roulette_clear: "LEEREN",
        roulette_search: "Helden suchen",
        roulette_selected: "Helden ausgewählt",
        roulette_build: "ROULETTE ERSTELLEN",
        roulette_pick_heroes: "Wähle mindestens einen Helden.",
        roulette_ready_help: "Konfiguriere und erstelle das Roulette vor dem Drehen.",
        roulette_built: "Roulette bereit.",
        roulette_winner: "Gewinner",
        roulette_custom_title: "BENUTZERDEFINIERTES HELDENROULETTE",
        roulette_spin_hint: "DREHEN",
        roulette_rule_note: "Jeder gewählte Held erscheint mindestens einmal; zusätzliche Felder wiederholen Helden aus der Auswahl.",
        roulette_entries: "NUMMERIERTE FELDER",
        roulette_not_built: "Erstelle das Roulette, um die nummerierten Felder zu sehen.",
        profile_connection: "PROFILVERKNÜPFUNG",
        manual: "MANUELL",
        synced: "MIT OVERFAST SYNCHRONISIERT",
        hybrid: "HYBRID",
        battletag: "BattleTag (Spieler#1234)",
        synchronize: "JETZT SYNCHRONISIEREN",
        lock: "SPERREN",
        unlock: "ENTSPERREN",
        manual_help: "Funktioniert lokal ohne BattleTag oder API.",
        synced_help: "OverFast aktualisiert alle Heldenkategorien.",
        hybrid_help: "OverFast aktualisiert freie Helden; manuelle Änderungen bleiben gesperrt.",
        sync_need_profile: "Wähle oder erstelle zuerst ein Profil.",
        sync_need_battletag: "Gib vor der Synchronisierung einen BattleTag ein.",
        sync_searching: "OverFast wird durchsucht und synchronisiert…",
        sync_loaded: "Profil synchronisiert.",
        sync_failed: "Synchronisierung fehlgeschlagen",
        sync_helper_warning: "Der lokale Helfer ist nicht verfügbar; der manuelle Modus funktioniert weiter.",
        sync_save_failed: "Synchronisierung konnte nicht gespeichert werden",
        heroes_updated: "Helden aktualisiert",
        classification_note: "Main ≥30 Std. · Verwendet ≥5 Std. · In Übung >0 Std. · Unbenutzt 0 Std.",
        relevant_use_note: "Relevante Nutzung: 5 Stunden",
        linked_profile: "BattleTag mit dem aktuellen Profil verknüpft.",
        link_profile: "MIT AKTUELLEM PROFIL VERKNÜPFEN",
        player: "Spieler",
        roulette: "ROULETTE", statistics: "STATISTIKEN", player_search: "SPIELER SUCHEN",
        search_hint: "BattleTag oder Spielername", search: "SUCHEN", load_direct: "ID LADEN",
        search_results: "SUCHERGEBNISSE", no_results: "Keine Spieler gefunden.", select_player: "Wähle einen Spieler aus, um Statistiken anzuzeigen.",
        profile_private: "Das Karriereprofil ist privat oder enthält keine sichtbaren Statistiken.",
        overview: "ÜBERSICHT", heroes: "HELDENNUTZUNG", roles: "ROLLEN", career: "KARRIERE", api: "OVERFAST API",
        all_modes: "Alle Modi", quickplay: "Schnellsuche", competitive: "Rangliste",
        all_platforms: "Alle Plattformen", pc: "PC", console: "Konsole", refresh: "AKTUALISIEREN",
        time_played: "Spielzeit", games: "Spiele", wins: "Siege", losses: "Niederlagen", winrate: "Siegquote", kda: "KDA",
        eliminations: "Eliminierungen", assists: "Assists", deaths: "Tode", damage: "Schaden", healing: "Heilung",
        usage: "Nutzung", last_updated: "Zuletzt aktualisiert", endorsement: "Anerkennung", rank: "Ranglistenränge",
        no_stats: "Für diese Filter sind keine sichtbaren Statistiken vorhanden.", no_comp: "Kein sichtbarer Ranglistenrang.",
        career_mode_note: "Karrieredetails benötigen einen Modus. Wähle einen Helden oder alle Helden.",
        hero: "Held", all_heroes: "Alle Helden", load_career: "KARRIEREDATEN LADEN",
        endpoint: "Endpunkt", run_endpoint: "ENDPUNKT AUSFÜHREN", response_preview: "ANTWORTVORSCHAU",
        response_truncated: "Die Vorschau wurde gekürzt, damit die Oberfläche flüssig bleibt.",
        searching: "Suche über OverFast…", loading: "Spielerdaten werden geladen…", loaded: "Spielerdaten geladen.",
        request_failed: "OverFast-Anfrage fehlgeschlagen", invalid_id: "Gib einen BattleTag oder eine Spieler-ID ein.",
        api_note: "Die Daten stammen aus der OverFast API und öffentlichen Blizzard-Karriereprofilen. Private Profile können nicht gelesen werden.",
        category: "Kategorie", value: "Wert", public_profile: "Öffentliches Profil", private_profile: "Privates Profil",
        direct_help: "Im BattleTag kann # oder - verwendet werden. Beispiel: Spieler#1234 oder Spieler-1234.",
        top_hero: "Meistgespielter Held", total_usage: "Anteil an der sichtbaren Gesamtspielzeit", season: "Saison",
        player_id: "Spieler-ID", title: "Titel", open_queue: "Offene Rollenwahl", tank: "Tank", support: "Unterstützung"
    },
    "ko-kr": {
        bucket_main: "Main",
        bucket_used: "사용",
        bucket_practice: "연습 중",
        bucket_unused: "미사용",
        principal: "메인",
        roulette_format: "룰렛",
        spin_roulette: "룰렛 돌리기",
        roulette_spinning: "회전 중…",

        roulette_maker_short: "제작",
        roulette_maker: "룰렛 제작기",
        roulette_numbers: "번호 칸의 정확한 개수를 선택하세요.",
        roulette_weight_hint: "각 영웅의 - 와 + 로 칸 수를 정하세요. 확률은 자동으로 계산됩니다.",
        roulette_slots: "칸",
        roulette_roles: "허용 역할",
        roulette_select_all: "모두 선택",
        roulette_clear: "지우기",
        roulette_search: "영웅 검색",
        roulette_selected: "명의 영웅 선택",
        roulette_build: "룰렛 만들기",
        roulette_pick_heroes: "영웅을 한 명 이상 선택하세요.",
        roulette_ready_help: "룰렛을 설정하고 만든 뒤 돌리세요.",
        roulette_built: "룰렛 준비 완료.",
        roulette_winner: "당첨",
        roulette_custom_title: "사용자 지정 영웅 룰렛",
        roulette_spin_hint: "돌리기",
        roulette_rule_note: "선택한 영웅은 각각 최소 한 번 나오며, 남는 칸은 선택한 영웅을 반복합니다.",
        roulette_entries: "번호 칸",
        roulette_not_built: "룰렛을 만들면 번호 칸이 표시됩니다.",
        profile_connection: "프로필 연결",
        manual: "수동",
        synced: "OVERFAST 동기화",
        hybrid: "하이브리드",
        battletag: "BattleTag (Player#1234)",
        synchronize: "지금 동기화",
        lock: "잠금",
        unlock: "해제",
        manual_help: "BattleTag나 API 없이 로컬에서 작동합니다.",
        synced_help: "OverFast가 모든 영웅 분류를 업데이트합니다.",
        hybrid_help: "잠기지 않은 영웅만 동기화하고 수동 변경은 유지합니다.",
        sync_need_profile: "먼저 프로필을 선택하거나 만드세요.",
        sync_need_battletag: "동기화 전에 BattleTag를 입력하세요.",
        sync_searching: "OverFast 검색 및 동기화 중…",
        sync_loaded: "프로필을 동기화했습니다.",
        sync_failed: "동기화 실패",
        sync_helper_warning: "로컬 도우미를 사용할 수 없습니다. 수동 모드는 계속 작동합니다.",
        sync_save_failed: "동기화 설정을 저장하지 못했습니다",
        heroes_updated: "명의 영웅 업데이트",
        classification_note: "Main 30시간 이상 · 사용 5시간 이상 · 연습 0시간 초과 · 미사용 0시간",
        relevant_use_note: "유의미한 사용 기준: 5시간",
        linked_profile: "BattleTag를 현재 프로필에 연결했습니다.",
        link_profile: "현재 프로필에 연결",
        player: "플레이어",
        roulette: "룰렛", statistics: "통계", player_search: "플레이어 검색",
        search_hint: "BattleTag 또는 플레이어 이름", search: "검색", load_direct: "ID 불러오기",
        search_results: "검색 결과", no_results: "플레이어를 찾지 못했습니다.", select_player: "통계를 볼 플레이어를 선택하세요.",
        profile_private: "경력 프로필이 비공개이거나 표시할 통계가 없습니다.",
        overview: "요약", heroes: "영웅 사용량", roles: "역할", career: "경력", api: "OVERFAST API",
        all_modes: "모든 모드", quickplay: "빠른 대전", competitive: "경쟁전",
        all_platforms: "모든 플랫폼", pc: "PC", console: "콘솔", refresh: "새로고침",
        time_played: "플레이 시간", games: "게임", wins: "승리", losses: "패배", winrate: "승률", kda: "KDA",
        eliminations: "처치", assists: "도움", deaths: "죽음", damage: "피해", healing: "치유",
        usage: "사용률", last_updated: "마지막 업데이트", endorsement: "추천 레벨", rank: "경쟁전 등급",
        no_stats: "이 필터에서 표시할 통계가 없습니다.", no_comp: "표시할 경쟁전 등급이 없습니다.",
        career_mode_note: "경력 세부 정보에는 게임 모드가 필요합니다. 영웅 또는 모든 영웅을 선택하세요.",
        hero: "영웅", all_heroes: "모든 영웅", load_career: "경력 세부 정보 불러오기",
        endpoint: "엔드포인트", run_endpoint: "실행", response_preview: "응답 미리보기",
        response_truncated: "화면 성능을 위해 미리보기를 줄였습니다.",
        searching: "OverFast에서 검색 중…", loading: "플레이어 데이터 불러오는 중…", loaded: "플레이어 데이터를 불러왔습니다.",
        request_failed: "OverFast 요청 실패", invalid_id: "BattleTag 또는 플레이어 ID를 입력하세요.",
        api_note: "데이터는 OverFast API와 Blizzard의 공개 경력 프로필에서 가져옵니다. 비공개 프로필은 읽을 수 없습니다.",
        category: "범주", value: "값", public_profile: "공개 프로필", private_profile: "비공개 프로필",
        direct_help: "BattleTag에 # 또는 -를 사용할 수 있습니다. 예: Player#1234 / Player-1234",
        top_hero: "가장 많이 플레이한 영웅", total_usage: "표시 가능한 전체 플레이 시간 비율", season: "시즌",
        player_id: "플레이어 ID", title: "칭호", open_queue: "자유 역할", tank: "돌격", support: "지원"
    }
};

function t(locale, key) {
    var map = strings[locale] || strings["en-us"];
    return map[key] !== undefined ? map[key] : (strings["en-us"][key] !== undefined ? strings["en-us"][key] : key);
}
