.pragma library

var rows = [
    { hero: "Ana", en: "Aysha Selim", latam: "Andrea Coto; Yolanda Vidal (Retribution)" },
    { hero: "Anran", en: "Fareeha Andersen", latam: "Lolo Muñoz; Alicia Barragán (Elemental Kin)" },
    { hero: "Ashe", en: "Jennifer Hale", latam: "Ale Delint" },
    { hero: "Baptiste", en: "Benz Antoine", latam: "Gabriel Basurto" },
    { hero: "Bastion", en: "Chris Metzen", latam: "Sin acreditación latina disponible" },
    { hero: "Brigitte", en: "Matilda Smedius", latam: "Annie Rojas" },
    { hero: "Cassidy", en: "Matthew Mercer", latam: "José Arenas; David Caramillo" },
    { hero: "D.Va", en: "Charlet Chung", latam: "Meli G" },
    { hero: "Domina", en: "Taj Atwal", latam: "Luciana Falcón" },
    { hero: "Doomfist", en: "Sahr Ngaujah", latam: "Juan Carlos Tinoco" },
    { hero: "Echo", en: "Jeannie Bolet", latam: "Jessica Ángeles" },
    { hero: "Emre", en: "Kerem Erdinc", latam: "Alejandro Graue" },
    { hero: "Freja", en: "Olivia Le Andersen", latam: "Dafne Gallardo" },
    { hero: "Genji", en: "Gaku Space", latam: "Óscar Flores; Carlos Olízar; Abraham Vega" },
    { hero: "Hanzo", en: "Paul Nakauchi", latam: "Dan Osorio" },
    { hero: "Hazard", en: "Conor McLeod", latam: "Julio Grijalva" },
    { hero: "Illari", en: "Andre Cisneros", latam: "Andre Cisneros" },
    { hero: "Jetpack Cat", en: "Jennifer Hale", latam: "Sin acreditación latina disponible" },
    { hero: "Junker Queen", en: "Leah de Niese", latam: "Betzabé Jara" },
    { hero: "Junkrat", en: "Chris Parson", latam: "Alfonso Obregón; Geezuz González; Tommy Rojas" },
    { hero: "Juno", en: "Xanthe Huynh", latam: "Desireé González" },
    { hero: "Kiriko", en: "Sally Amaki", latam: "Yetzary Olcort" },
    { hero: "Lifeweaver", en: "Phuwin Tangsakyuen", latam: "Oscar Garibay" },
    { hero: "Lúcio", en: "Jonny Cruz", latam: "Lalo Garza" },
    { hero: "Mauga", en: "John Tui", latam: "Rolando de Castro" },
    { hero: "Mei", en: "Elise Zhang", latam: "Joanna Ruvalcaba" },
    { hero: "Mercy", en: "Lucie Pohl", latam: "Circe Luna" },
    { hero: "Mizuki", en: "Julian Cihi", latam: "Braian Pavón" },
    { hero: "Moira", en: "Genevieve O'Reilly", latam: "Sarah Souza" },
    { hero: "Orisa", en: "Cherrelle Skeete", latam: "Vanessa Acosta; Yadira Aedo" },
    { hero: "Pharah", en: "Jen Cohn", latam: "Irina Índigo" },
    { hero: "Ramattra", en: "Ramon Tikaram", latam: "Beto Castillo" },
    { hero: "Reaper", en: "Keith Ferguson", latam: "José Luis Orozco; Humberto Vélez" },
    { hero: "Reinhardt", en: "Darin De Paul", latam: "Humberto Solórzano" },
    { hero: "Roadhog", en: "Josh Petersdorf", latam: "Miguel Ángel Ghigliazza; Víctor Hugo Aguilar; César Soto" },
    { hero: "Shion", en: "Mariko Baika", latam: "Carolina Taliberti" },
    { hero: "Sierra", en: "Khaya Fraites", latam: "Violeta Bronca" },
    { hero: "Sigma", en: "Boris Hiestand", latam: "Raúl Anaya" },
    { hero: "Sojourn", en: "Cherise Boothe", latam: "Rommy Mendoza" },
    { hero: "Soldier: 76", en: "Fred Tatasciore", latam: "Carlos Segundo" },
    { hero: "Sombra", en: "Carolina Ravassa", latam: "Lourdes Arruti" },
    { hero: "Symmetra", en: "Anjali Bhimani", latam: "Carla Castañeda" },
    { hero: "Torbjörn", en: "Keith Silverstein", latam: "Arturo Mercado Chacón" },
    { hero: "Tracer", en: "Cara Theobold", latam: "Analiz Sánchez" },
    { hero: "Vendetta", en: "Chiara Preziose", latam: "María Ayuso" },
    { hero: "Venture", en: "Valeria Rodriguez", latam: "Stephan Coronel" },
    { hero: "Widowmaker", en: "Chloé Hollings", latam: "Erica Edwards" },
    { hero: "Winston", en: "Crispin Freeman", latam: "Arturo Casanova; Jorge Lapuente; René Sagástume" },
    { hero: "Wrecking Ball", en: "Dee Bradley Baker (Hammond); Jonathan Lipow (robot)", latam: "Santos Alberto (robot)" },
    { hero: "Wuyang", en: "Howard Wang", latam: "Eduardo Martínez" },
    { hero: "Zarya", en: "Dolya Gavanski", latam: "Laura Torres; Kerygma Flores" },
    { hero: "Zenyatta", en: "Feodor Chin", latam: "Arturo Mercado Jr." }
]
