export type PvzSide = 'plants' | 'zombies'

export type PvzCharacter = {
  key: string
  name: string
  side: PvzSide
  baseKey: string
  baseName: string
  isVariant: boolean
  isDlc: boolean
  portrait: string
}

const rows: PvzCharacter[] = [
  {key: "plant-1-citron", name: "Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-1-citron.png"},
  {key: "plant-2-frozen-citron", name: "Frozen Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-2-frozen-citron.png"},
  {key: "plant-3-electro-citron", name: "Electro Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-3-electro-citron.png"},
  {key: "plant-4-iron-citron", name: "Iron Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-4-iron-citron.png"},
  {key: "plant-5-party-citron", name: "Party Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-5-party-citron.png"},
  {key: "plant-6-toxic-citron", name: "Toxic Citron", side: "plants", baseKey: "plant-1-citron", baseName: "Citron", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-6-toxic-citron.png"},
  {key: "plant-7-rose", name: "Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-7-rose.png"},
  {key: "plant-8-druid-rose", name: "Druid Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-8-druid-rose.png"},
  {key: "plant-9-fire-rose", name: "Fire Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-9-fire-rose.png"},
  {key: "plant-10-frost-rose", name: "Frost Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-10-frost-rose.png"},
  {key: "plant-11-party-rose", name: "Party Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-11-party-rose.png"},
  {key: "plant-12-nec-rose", name: "Nec'Rose", side: "plants", baseKey: "plant-7-rose", baseName: "Rose", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-12-nec-rose.png"},
  {key: "plant-13-kernel-corn", name: "Kernel Corn", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-13-kernel-corn.png"},
  {key: "plant-14-bbq-corn", name: "BBQ Corn", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-14-bbq-corn.png"},
  {key: "plant-15-mob-cob", name: "Mob Cob", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-15-mob-cob.png"},
  {key: "plant-16-pops-corn", name: "Pops Corn", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-16-pops-corn.png"},
  {key: "plant-17-party-corn", name: "Party Corn", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-17-party-corn.png"},
  {key: "plant-18-commando-corn", name: "Commando Corn", side: "plants", baseKey: "plant-13-kernel-corn", baseName: "Kernel Corn", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-18-commando-corn.png"},
  {key: "plant-19-peashooter", name: "Peashooter", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-19-peashooter.png"},
  {key: "plant-20-fire-pea", name: "Fire Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-20-fire-pea.png"},
  {key: "plant-21-ice-pea", name: "Ice Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-21-ice-pea.png"},
  {key: "plant-22-toxic-pea", name: "Toxic Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-22-toxic-pea.png"},
  {key: "plant-23-commando-pea", name: "Commando Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-23-commando-pea.png"},
  {key: "plant-24-agent-pea", name: "Agent Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-24-agent-pea.png"},
  {key: "plant-25-law-pea", name: "Law Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-25-law-pea.png"},
  {key: "plant-26-plasma-pea", name: "Plasma Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-26-plasma-pea.png"},
  {key: "plant-27-rock-pea", name: "Rock Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-27-rock-pea.png"},
  {key: "plant-28-electro-pea", name: "Electro Pea", side: "plants", baseKey: "plant-19-peashooter", baseName: "Peashooter", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-28-electro-pea.png"},
  {key: "plant-29-chomper", name: "Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-29-chomper.png"},
  {key: "plant-30-fire-chomper", name: "Fire Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-30-fire-chomper.png"},
  {key: "plant-31-hot-rod-chomper", name: "Hot Rod Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-31-hot-rod-chomper.png"},
  {key: "plant-32-power-chomper", name: "Power Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-32-power-chomper.png"},
  {key: "plant-33-count-chompula", name: "Count Chompula", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-33-count-chompula.png"},
  {key: "plant-34-toxic-chomper", name: "Toxic Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-34-toxic-chomper.png"},
  {key: "plant-35-armor-chomper", name: "Armor Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-35-armor-chomper.png"},
  {key: "plant-36-chomp-thing", name: "Chomp Thing", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-36-chomp-thing.png"},
  {key: "plant-37-yeti-chomper", name: "Yeti Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-37-yeti-chomper.png"},
  {key: "plant-38-disco-chomper", name: "Disco Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-38-disco-chomper.png"},
  {key: "plant-39-unicorn-chomper", name: "Unicorn Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: true, portrait: "assets/pvzgw2/characters/plant-39-unicorn-chomper.png"},
  {key: "plant-40-twilight-chomper", name: "Twilight Chomper", side: "plants", baseKey: "plant-29-chomper", baseName: "Chomper", isVariant: true, isDlc: true, portrait: "assets/pvzgw2/characters/plant-40-twilight-chomper.png"},
  {key: "plant-41-sunflower", name: "Sunflower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-41-sunflower.png"},
  {key: "plant-42-fire-flower", name: "Fire Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-42-fire-flower.png"},
  {key: "plant-43-power-flower", name: "Power Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-43-power-flower.png"},
  {key: "plant-44-shadow-flower", name: "Shadow Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-44-shadow-flower.png"},
  {key: "plant-45-mystic-flower", name: "Mystic Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-45-mystic-flower.png"},
  {key: "plant-46-metal-petal", name: "Metal Petal", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-46-metal-petal.png"},
  {key: "plant-47-sun-pharaoh", name: "Sun Pharaoh", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-47-sun-pharaoh.png"},
  {key: "plant-48-alien-flower", name: "Alien Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-48-alien-flower.png"},
  {key: "plant-49-vampire-flower", name: "Vampire Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-49-vampire-flower.png"},
  {key: "plant-50-stuffy-flower", name: "Stuffy Flower", side: "plants", baseKey: "plant-41-sunflower", baseName: "Sunflower", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-50-stuffy-flower.png"},
  {key: "plant-51-cactus", name: "Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/plant-51-cactus.png"},
  {key: "plant-52-fire-cactus", name: "Fire Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-52-fire-cactus.png"},
  {key: "plant-53-ice-cactus", name: "Ice Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-53-ice-cactus.png"},
  {key: "plant-54-power-cactus", name: "Power Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-54-power-cactus.png"},
  {key: "plant-55-future-cactus", name: "Future Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-55-future-cactus.png"},
  {key: "plant-56-camo-cactus", name: "Camo Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-56-camo-cactus.png"},
  {key: "plant-57-bandit-cactus", name: "Bandit Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-57-bandit-cactus.png"},
  {key: "plant-58-jade-cactus", name: "Jade Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-58-jade-cactus.png"},
  {key: "plant-59-zen-cactus", name: "Zen Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-59-zen-cactus.png"},
  {key: "plant-60-petrified-cactus", name: "Petrified Cactus", side: "plants", baseKey: "plant-51-cactus", baseName: "Cactus", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/plant-60-petrified-cactus.png"},
  {key: "plant-61-torchwood", name: "Torchwood", side: "plants", baseKey: "plant-61-torchwood", baseName: "Torchwood", isVariant: false, isDlc: true, portrait: "assets/pvzgw2/characters/plant-61-torchwood.png"},
  {key: "zombie-1-imp", name: "Imp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-1-imp.png"},
  {key: "zombie-2-lil--drake", name: "Lil' Drake", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-2-lil--drake.png"},
  {key: "zombie-3-pylon-imp", name: "Pylon Imp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-3-pylon-imp.png"},
  {key: "zombie-4-shrimp", name: "Shrimp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-4-shrimp.png"},
  {key: "zombie-5-z7-imp", name: "Z7 Imp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: true, portrait: "assets/pvzgw2/characters/zombie-5-z7-imp.png"},
  {key: "zombie-6-party-imp", name: "Party Imp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-6-party-imp.png"},
  {key: "zombie-7-scallywag-imp", name: "Scallywag Imp", side: "zombies", baseKey: "zombie-1-imp", baseName: "Imp", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-7-scallywag-imp.png"},
  {key: "zombie-8-super-brainz", name: "Super Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-8-super-brainz.png"},
  {key: "zombie-9-cozmic-brainz", name: "Cozmic Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-9-cozmic-brainz.png"},
  {key: "zombie-10-electro-brainz", name: "Electro Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-10-electro-brainz.png"},
  {key: "zombie-11-toxic-brainz", name: "Toxic Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-11-toxic-brainz.png"},
  {key: "zombie-12-party-brainz", name: "Party Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-12-party-brainz.png"},
  {key: "zombie-13-breakfast-brainz", name: "Breakfast Brainz", side: "zombies", baseKey: "zombie-8-super-brainz", baseName: "Super Brainz", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-13-breakfast-brainz.png"},
  {key: "zombie-14-captain-deadbeard", name: "Captain Deadbeard", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-14-captain-deadbeard.png"},
  {key: "zombie-15-captain-cannon", name: "Captain Cannon", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-15-captain-cannon.png"},
  {key: "zombie-16-captain-flameface", name: "Captain Flameface", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-16-captain-flameface.png"},
  {key: "zombie-17-captain-sharkbite", name: "Captain Sharkbite", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-17-captain-sharkbite.png"},
  {key: "zombie-18-captain-partyman", name: "Captain Partyman", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-18-captain-partyman.png"},
  {key: "zombie-19-captain-squawk", name: "Captain Squawk", side: "zombies", baseKey: "zombie-14-captain-deadbeard", baseName: "Captain Deadbeard", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-19-captain-squawk.png"},
  {key: "zombie-20-foot-soldier", name: "Foot Soldier", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-20-foot-soldier.png"},
  {key: "zombie-21-super-commando", name: "Super Commando", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-21-super-commando.png"},
  {key: "zombie-22-arctic-trooper", name: "Arctic Trooper", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-22-arctic-trooper.png"},
  {key: "zombie-23-tank-commander", name: "Tank Commander", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-23-tank-commander.png"},
  {key: "zombie-24-general-surpremo", name: "General Supremo", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-24-general-surpremo.png"},
  {key: "zombie-25-camo-ranger", name: "Camo Ranger", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-25-camo-ranger.png"},
  {key: "zombie-26-sky-trooper", name: "Sky Trooper", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-26-sky-trooper.png"},
  {key: "zombie-27-centurion", name: "Centurion", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-27-centurion.png"},
  {key: "zombie-28-park-ranger", name: "Park Ranger", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-28-park-ranger.png"},
  {key: "zombie-29-scuba-soldier", name: "Scuba Soldier", side: "zombies", baseKey: "zombie-20-foot-soldier", baseName: "Foot Soldier", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-29-scuba-soldier.png"},
  {key: "zombie-30-engineer", name: "Engineer", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-30-engineer.png"},
  {key: "zombie-31-welder", name: "Welder", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-31-welder.png"},
  {key: "zombie-33-electrician", name: "Electrician", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-33-electrician.png"},
  {key: "zombie-33-mechanic", name: "Mechanic", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-33-mechanic.png"},
  {key: "zombie-34-painter", name: "Painter", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-34-painter.png"},
  {key: "zombie-35-plumber", name: "Plumber", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-35-plumber.png"},
  {key: "zombie-36-landscaper", name: "Landscaper", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-36-landscaper.png"},
  {key: "zombie-37-sanitation-expert", name: "Sanitation Expert", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-37-sanitation-expert.png"},
  {key: "zombie-38-roadie-z", name: "Roadie Z", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-38-roadie-z.png"},
  {key: "zombie-39-ac-perry", name: "AC Perry", side: "zombies", baseKey: "zombie-30-engineer", baseName: "Engineer", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-39-ac-perry.png"},
  {key: "zombie-40-scientist", name: "Scientist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-40-scientist.png"},
  {key: "zombie-41-marine-biologist", name: "Marine Biologist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-41-marine-biologist.png"},
  {key: "zombie-42-dr-toxic", name: "Dr. Toxic", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-42-dr-toxic.png"},
  {key: "zombie-43-physicist", name: "Physicist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-43-physicist.png"},
  {key: "zombie-44-astronaut", name: "Astronaut", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-44-astronaut.png"},
  {key: "zombie-45-chemist", name: "Chemist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-45-chemist.png"},
  {key: "zombie-46-archaeologist", name: "Archaeologist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-46-archaeologist.png"},
  {key: "zombie-47-paleontologist", name: "Paleontologist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-47-paleontologist.png"},
  {key: "zombie-48-zoologist", name: "Zoologist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-48-zoologist.png"},
  {key: "zombie-49-computer-scientist", name: "Computer Scientist", side: "zombies", baseKey: "zombie-40-scientist", baseName: "Scientist", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-49-computer-scientist.png"},
  {key: "zombie-50-all-star", name: "All Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: false, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-50-all-star.png"},
  {key: "zombie-51-cricket-star", name: "Cricket Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-51-cricket-star.png"},
  {key: "zombie-52-goalie-star", name: "Goalie Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-52-goalie-star.png"},
  {key: "zombie-53-baseball-star", name: "Baseball Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-53-baseball-star.png"},
  {key: "zombie-54-hockey-star", name: "Hockey Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-54-hockey-star.png"},
  {key: "zombie-55-rugby-star", name: "Rugby Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-55-rugby-star.png"},
  {key: "zombie-56-wrestling-star", name: "Wrestling Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-56-wrestling-star.png"},
  {key: "zombie-57-golf-star", name: "Golf Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-57-golf-star.png"},
  {key: "zombie-58-moto-x-star", name: "Moto X Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-58-moto-x-star.png"},
  {key: "zombie-59-tennis-star", name: "Tennis Star", side: "zombies", baseKey: "zombie-50-all-star", baseName: "All Star", isVariant: true, isDlc: false, portrait: "assets/pvzgw2/characters/zombie-59-tennis-star.png"},
  {key: "zombie-60-hover-goat-3000", name: "Hover Goat-3000", side: "zombies", baseKey: "zombie-60-hover-goat-3000", baseName: "Hover Goat-3000", isVariant: false, isDlc: true, portrait: "assets/pvzgw2/characters/zombie-60-hover-goat-3000.png"},
]

export const pvzCharacters = rows

export const pvzSideLabels: Record<PvzSide, string> = { plants: 'Plantas', zombies: 'Zombis' }

export const pvzSideSingular: Record<PvzSide, string> = { plants: 'Planta', zombies: 'Zombi' }

export const pvzSideColors: Record<PvzSide, string> = { plants: '#71d56b', zombies: '#a985dd' }

export const pvzPalettes: Record<PvzSide, string[]> = {
  plants: ['#71d56b', '#4fab61', '#9ce66d', '#3b9258', '#b5e878', '#64bd72', '#88dc91', '#3f7e4e'],
  zombies: ['#a985dd', '#8466bc', '#c39cec', '#6c55a5', '#b98be0', '#7453a8', '#d3b2f0', '#574287'],
}
